version: '3'
services:
  dev:
    tty: false
    stdin_open: true

    container_name: ACdev
    build:
      context: .
      dockerfile: Dockerfile

    # イメージ名を指定
    image: atcoder_cpp

    # localとcontainer間のファイルを同期させる
    # ${local}:${container}
    volumes:
      - ../CPLUS:/root/problems:cached #../problems:/root/problems:cached
      - ../.library:/root/library:cached #../library:/root/library:cached
    #  - ../acc-template-python:/root/.config/atcoder-cli-nodejs/python:cached
      - ../CPLUS/.vscode:/root/.vscode:cached

    # オプション これらのconfigファイルが必要なければコメントアウト
    # - ../dotfiles/.zshrc:/root/.zshrc
    # - ../dotfiles/.zinit:/root/.zinit
    # - ../dotfiles/.zsh_history:/root/.zsh_history
    # - ../dotfiles/.aliases:/root/.aliases

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/bash
    #command: /bin/sh -c "while sleep 1000; do :; done"
